version: '3'

services:
  frontend:
    restart: always
    image: ${CR_HOST}/${CR_USERNAME}/delivery-help-frontend:staging
    command: nginx -g 'daemon off;'
    env_file: ${HOME}/delivery-help/.env
    ports:
      - 80:80

  backend:
    restart: always
    image: ${CR_HOST}/${CR_USERNAME}/delivery-help-backend:staging
    command: npm run start
    env_file: ${HOME}/delivery-help/.env
    volumes:
      - /tmp/delivery-help:/app-tmp
    depends_on:
      - mongo

mongo:
  image: mongo:5.0.7
  volumes:
    - data_mongo:/data/db
  env_file: .env
  environment:
    MONGO_INITDB_ROOT_USERNAME: 'admin'
    MONGO_INITDB_ROOT_PASSWORD: 'admin'

volumes:
  data_mongo:
    driver: local