version: '3'

services:
  frontend:
    restart: always
    image: ${FRONTEND_IMAGE}:${APP_VERSION}
    command: nginx -g 'daemon off;'
    env_file: .env
    ports:
      - 80:80

  backend:
    restart: always
    image: ${BACKEND_IMAGE}:${APP_VERSION}
    command: node dist/main
    env_file: .env
    volumes:
      - /tmp/delivery-help:/app-tmp
    depends_on:
      - postgres

  postgres:
    image: postgres:14.6-alpine
    volumes:
      - data-postgres:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_PASSWORD: password

volumes:
  data-postgres:
    driver: local
