version: '3'

services:
  frontend:
    restart: always
    image: ${FRONTEND_IMAGE}:${APP_VERSION}
    command: nginx -g 'daemon off;'
    env_file: .env
    ports:
      - 80:80

  backend:
    restart: always
    image: ${BACKEND_IMAGE}:${APP_VERSION}
    command: node dist/main
    env_file: .env
    volumes:
      - /tmp/delivery-help:/app-tmp
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0.7
    volumes:
      - data_mongo:/data/db
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'admin'

volumes:
  data_mongo:
    driver: local