version: '3'

services:
  frontend:
    restart: always
    image: ${CR_HOST}/${CR_USERNAME}/delivery-help-frontend:staging
    command: nginx -g 'daemon off;'
    env_file: ${HOME}/delivery-help/.env
    ports:
      - 80:80

  backend:
    restart: always
    image: ${CR_HOST}/${CR_USERNAME}/delivery-help-backend:production
    command: node dist/main
    env_file: ${HOME}/delivery-help/.env
    volumes:
      - /tmp/delivery-help:/app-tmp
