version: '3'

services:
  frontend:
    restart: always
    image: ${FRONTEND_IMAGE}:${APP_VERSION}
    command: nginx -g 'daemon off;'
    env_file: .env
    ports:
      - 80:80

  backend:
    restart: always
    image: ${BACKEND_IMAGE}:${APP_VERSION}
    command: node dist/main
    env_file: .env
    volumes:
      - /tmp/delivery-help:/app-tmp
